//! Vulkan 1.3 — Enumerations (C ABI)

/// VkResult values
pub const VK_RESULT_VALUES: &[(&str, &str)] = &[
    ("VK_SUCCESS", "0"),
    ("VK_NOT_READY", "1"),
    ("VK_TIMEOUT", "2"),
    ("VK_EVENT_SET", "3"),
    ("VK_EVENT_RESET", "4"),
    ("VK_INCOMPLETE", "5"),
    ("VK_ERROR_OUT_OF_HOST_MEMORY", "-1"),
    ("VK_ERROR_OUT_OF_DEVICE_MEMORY", "-2"),
    ("VK_ERROR_INITIALIZATION_FAILED", "-3"),
    ("VK_ERROR_DEVICE_LOST", "-4"),
    ("VK_ERROR_MEMORY_MAP_FAILED", "-5"),
    ("VK_ERROR_LAYER_NOT_PRESENT", "-6"),
    ("VK_ERROR_EXTENSION_NOT_PRESENT", "-7"),
    ("VK_ERROR_FEATURE_NOT_PRESENT", "-8"),
    ("VK_ERROR_INCOMPATIBLE_DRIVER", "-9"),
    ("VK_ERROR_TOO_MANY_OBJECTS", "-10"),
    ("VK_ERROR_FORMAT_NOT_SUPPORTED", "-11"),
    ("VK_ERROR_FRAGMENTED_POOL", "-12"),
    ("VK_ERROR_OUT_OF_POOL_MEMORY", "-1000069000"),
    ("VK_ERROR_INVALID_EXTERNAL_HANDLE", "-1000072003"),
    ("VK_ERROR_FRAGMENTATION", "-1000161000"),
    ("VK_ERROR_INVALID_OPAQUE_CAPTURE_ADDRESS", "-1000257000"),
    ("VK_ERROR_SURFACE_LOST_KHR", "-1000000000"),
    ("VK_ERROR_NATIVE_WINDOW_IN_USE_KHR", "-1000000001"),
    ("VK_SUBOPTIMAL_KHR", "1000001003"),
    ("VK_ERROR_OUT_OF_DATE_KHR", "-1000001004"),
    ("VK_PIPELINE_COMPILE_REQUIRED", "1000297000"),
];

/// VkStructureType values
pub const VK_STRUCTURE_TYPES: &[(&str, &str)] = &[
    ("VK_STRUCTURE_TYPE_APPLICATION_INFO", "0"),
    ("VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO", "1"),
    ("VK_STRUCTURE_TYPE_DEVICE_QUEUE_CREATE_INFO", "2"),
    ("VK_STRUCTURE_TYPE_DEVICE_CREATE_INFO", "3"),
    ("VK_STRUCTURE_TYPE_SUBMIT_INFO", "4"),
    ("VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO", "5"),
    ("VK_STRUCTURE_TYPE_MAPPED_MEMORY_RANGE", "6"),
    ("VK_STRUCTURE_TYPE_BIND_SPARSE_INFO", "7"),
    ("VK_STRUCTURE_TYPE_FENCE_CREATE_INFO", "8"),
    ("VK_STRUCTURE_TYPE_SEMAPHORE_CREATE_INFO", "9"),
    ("VK_STRUCTURE_TYPE_EVENT_CREATE_INFO", "10"),
    ("VK_STRUCTURE_TYPE_QUERY_POOL_CREATE_INFO", "11"),
    ("VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO", "12"),
    ("VK_STRUCTURE_TYPE_BUFFER_VIEW_CREATE_INFO", "13"),
    ("VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO", "14"),
    ("VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO", "15"),
    ("VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO", "16"),
    ("VK_STRUCTURE_TYPE_PIPELINE_CACHE_CREATE_INFO", "17"),
    ("VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO", "18"),
    ("VK_STRUCTURE_TYPE_PIPELINE_VERTEX_INPUT_STATE_CREATE_INFO", "19"),
    ("VK_STRUCTURE_TYPE_PIPELINE_INPUT_ASSEMBLY_STATE_CREATE_INFO", "20"),
    ("VK_STRUCTURE_TYPE_PIPELINE_TESSELLATION_STATE_CREATE_INFO", "21"),
    ("VK_STRUCTURE_TYPE_PIPELINE_VIEWPORT_STATE_CREATE_INFO", "22"),
    ("VK_STRUCTURE_TYPE_PIPELINE_RASTERIZATION_STATE_CREATE_INFO", "23"),
    ("VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO", "24"),
    ("VK_STRUCTURE_TYPE_PIPELINE_DEPTH_STENCIL_STATE_CREATE_INFO", "25"),
    ("VK_STRUCTURE_TYPE_PIPELINE_COLOR_BLEND_STATE_CREATE_INFO", "26"),
    ("VK_STRUCTURE_TYPE_PIPELINE_DYNAMIC_STATE_CREATE_INFO", "27"),
    ("VK_STRUCTURE_TYPE_GRAPHICS_PIPELINE_CREATE_INFO", "28"),
    ("VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO", "29"),
    ("VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO", "30"),
    ("VK_STRUCTURE_TYPE_SAMPLER_CREATE_INFO", "31"),
    ("VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO", "32"),
    ("VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO", "33"),
    ("VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO", "34"),
    ("VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET", "35"),
    ("VK_STRUCTURE_TYPE_COPY_DESCRIPTOR_SET", "36"),
    ("VK_STRUCTURE_TYPE_FRAMEBUFFER_CREATE_INFO", "37"),
    ("VK_STRUCTURE_TYPE_RENDER_PASS_CREATE_INFO", "38"),
    ("VK_STRUCTURE_TYPE_COMMAND_POOL_CREATE_INFO", "39"),
    ("VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO", "40"),
    ("VK_STRUCTURE_TYPE_COMMAND_BUFFER_INHERITANCE_INFO", "41"),
    ("VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO", "42"),
    ("VK_STRUCTURE_TYPE_RENDER_PASS_BEGIN_INFO", "43"),
    ("VK_STRUCTURE_TYPE_BUFFER_MEMORY_BARRIER", "44"),
    ("VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER", "45"),
    ("VK_STRUCTURE_TYPE_MEMORY_BARRIER", "46"),
    ("VK_STRUCTURE_TYPE_SWAPCHAIN_CREATE_INFO_KHR", "1000001000"),
    ("VK_STRUCTURE_TYPE_PRESENT_INFO_KHR", "1000001001"),
    ("VK_STRUCTURE_TYPE_WIN32_SURFACE_CREATE_INFO_KHR", "1000009000"),
    ("VK_STRUCTURE_TYPE_XLIB_SURFACE_CREATE_INFO_KHR", "1000004000"),
    ("VK_STRUCTURE_TYPE_WAYLAND_SURFACE_CREATE_INFO_KHR", "1000006000"),
    // Vulkan 1.1
    ("VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SUBGROUP_PROPERTIES", "1000094000"),
    ("VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_16BIT_STORAGE_FEATURES", "1000083000"),
    ("VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MULTIVIEW_FEATURES", "1000053000"),
    // Vulkan 1.2
    ("VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VULKAN_1_1_FEATURES", "49"),
    ("VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VULKAN_1_1_PROPERTIES", "50"),
    ("VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VULKAN_1_2_FEATURES", "51"),
    ("VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VULKAN_1_2_PROPERTIES", "52"),
    // Vulkan 1.3
    ("VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VULKAN_1_3_FEATURES", "53"),
    ("VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VULKAN_1_3_PROPERTIES", "54"),
    ("VK_STRUCTURE_TYPE_RENDERING_INFO", "1000044000"),
    ("VK_STRUCTURE_TYPE_RENDERING_ATTACHMENT_INFO", "1000044001"),
    ("VK_STRUCTURE_TYPE_PIPELINE_RENDERING_CREATE_INFO", "1000044002"),
];

/// VkFormat values (commonly used)
pub const VK_FORMAT_VALUES: &[(&str, &str)] = &[
    ("VK_FORMAT_UNDEFINED", "0"),
    ("VK_FORMAT_R8_UNORM", "9"),
    ("VK_FORMAT_R8G8_UNORM", "16"),
    ("VK_FORMAT_R8G8B8_UNORM", "23"),
    ("VK_FORMAT_R8G8B8A8_UNORM", "37"),
    ("VK_FORMAT_R8G8B8A8_SRGB", "43"),
    ("VK_FORMAT_B8G8R8A8_UNORM", "44"),
    ("VK_FORMAT_B8G8R8A8_SRGB", "50"),
    ("VK_FORMAT_R16_SFLOAT", "76"),
    ("VK_FORMAT_R16G16_SFLOAT", "83"),
    ("VK_FORMAT_R16G16B16A16_SFLOAT", "97"),
    ("VK_FORMAT_R32_SFLOAT", "100"),
    ("VK_FORMAT_R32G32_SFLOAT", "103"),
    ("VK_FORMAT_R32G32B32_SFLOAT", "106"),
    ("VK_FORMAT_R32G32B32A32_SFLOAT", "109"),
    ("VK_FORMAT_D16_UNORM", "124"),
    ("VK_FORMAT_D32_SFLOAT", "126"),
    ("VK_FORMAT_D24_UNORM_S8_UINT", "129"),
    ("VK_FORMAT_D32_SFLOAT_S8_UINT", "130"),
];

/// Pipeline-related enums
pub const VK_PIPELINE_ENUMS: &[(&str, &str)] = &[
    // VkPrimitiveTopology
    ("VK_PRIMITIVE_TOPOLOGY_POINT_LIST", "0"),
    ("VK_PRIMITIVE_TOPOLOGY_LINE_LIST", "1"),
    ("VK_PRIMITIVE_TOPOLOGY_LINE_STRIP", "2"),
    ("VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST", "3"),
    ("VK_PRIMITIVE_TOPOLOGY_TRIANGLE_STRIP", "4"),
    ("VK_PRIMITIVE_TOPOLOGY_TRIANGLE_FAN", "5"),
    // VkPolygonMode
    ("VK_POLYGON_MODE_FILL", "0"),
    ("VK_POLYGON_MODE_LINE", "1"),
    ("VK_POLYGON_MODE_POINT", "2"),
    // VkCullModeFlagBits
    ("VK_CULL_MODE_NONE", "0"),
    ("VK_CULL_MODE_FRONT_BIT", "1"),
    ("VK_CULL_MODE_BACK_BIT", "2"),
    ("VK_CULL_MODE_FRONT_AND_BACK", "3"),
    // VkFrontFace
    ("VK_FRONT_FACE_COUNTER_CLOCKWISE", "0"),
    ("VK_FRONT_FACE_CLOCKWISE", "1"),
    // VkShaderStageFlagBits
    ("VK_SHADER_STAGE_VERTEX_BIT", "0x00000001"),
    ("VK_SHADER_STAGE_TESSELLATION_CONTROL_BIT", "0x00000002"),
    ("VK_SHADER_STAGE_TESSELLATION_EVALUATION_BIT", "0x00000004"),
    ("VK_SHADER_STAGE_GEOMETRY_BIT", "0x00000008"),
    ("VK_SHADER_STAGE_FRAGMENT_BIT", "0x00000010"),
    ("VK_SHADER_STAGE_COMPUTE_BIT", "0x00000020"),
    ("VK_SHADER_STAGE_ALL_GRAPHICS", "0x0000001F"),
    ("VK_SHADER_STAGE_ALL", "0x7FFFFFFF"),
    // VkDynamicState
    ("VK_DYNAMIC_STATE_VIEWPORT", "0"),
    ("VK_DYNAMIC_STATE_SCISSOR", "1"),
    ("VK_DYNAMIC_STATE_LINE_WIDTH", "2"),
    ("VK_DYNAMIC_STATE_DEPTH_BIAS", "3"),
    ("VK_DYNAMIC_STATE_BLEND_CONSTANTS", "4"),
    ("VK_DYNAMIC_STATE_STENCIL_REFERENCE", "8"),
    // VkPipelineBindPoint
    ("VK_PIPELINE_BIND_POINT_GRAPHICS", "0"),
    ("VK_PIPELINE_BIND_POINT_COMPUTE", "1"),
    ("VK_PIPELINE_BIND_POINT_RAY_TRACING_KHR", "1000165000"),
];

/// Memory-related enums
pub const VK_MEMORY_ENUMS: &[(&str, &str)] = &[
    // VkMemoryPropertyFlagBits
    ("VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT", "0x00000001"),
    ("VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT", "0x00000002"),
    ("VK_MEMORY_PROPERTY_HOST_COHERENT_BIT", "0x00000004"),
    ("VK_MEMORY_PROPERTY_HOST_CACHED_BIT", "0x00000008"),
    ("VK_MEMORY_PROPERTY_LAZILY_ALLOCATED_BIT", "0x00000010"),
    // VkBufferUsageFlagBits
    ("VK_BUFFER_USAGE_TRANSFER_SRC_BIT", "0x00000001"),
    ("VK_BUFFER_USAGE_TRANSFER_DST_BIT", "0x00000002"),
    ("VK_BUFFER_USAGE_UNIFORM_TEXEL_BUFFER_BIT", "0x00000004"),
    ("VK_BUFFER_USAGE_STORAGE_TEXEL_BUFFER_BIT", "0x00000008"),
    ("VK_BUFFER_USAGE_UNIFORM_BUFFER_BIT", "0x00000010"),
    ("VK_BUFFER_USAGE_STORAGE_BUFFER_BIT", "0x00000020"),
    ("VK_BUFFER_USAGE_INDEX_BUFFER_BIT", "0x00000040"),
    ("VK_BUFFER_USAGE_VERTEX_BUFFER_BIT", "0x00000080"),
    ("VK_BUFFER_USAGE_INDIRECT_BUFFER_BIT", "0x00000100"),
    // VkSharingMode
    ("VK_SHARING_MODE_EXCLUSIVE", "0"),
    ("VK_SHARING_MODE_CONCURRENT", "1"),
];

/// Image-related enums
pub const VK_IMAGE_ENUMS: &[(&str, &str)] = &[
    // VkImageType
    ("VK_IMAGE_TYPE_1D", "0"),
    ("VK_IMAGE_TYPE_2D", "1"),
    ("VK_IMAGE_TYPE_3D", "2"),
    // VkImageViewType
    ("VK_IMAGE_VIEW_TYPE_1D", "0"),
    ("VK_IMAGE_VIEW_TYPE_2D", "1"),
    ("VK_IMAGE_VIEW_TYPE_3D", "2"),
    ("VK_IMAGE_VIEW_TYPE_CUBE", "3"),
    ("VK_IMAGE_VIEW_TYPE_1D_ARRAY", "4"),
    ("VK_IMAGE_VIEW_TYPE_2D_ARRAY", "5"),
    ("VK_IMAGE_VIEW_TYPE_CUBE_ARRAY", "6"),
    // VkImageLayout
    ("VK_IMAGE_LAYOUT_UNDEFINED", "0"),
    ("VK_IMAGE_LAYOUT_GENERAL", "1"),
    ("VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL", "2"),
    ("VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL", "3"),
    ("VK_IMAGE_LAYOUT_DEPTH_STENCIL_READ_ONLY_OPTIMAL", "4"),
    ("VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL", "5"),
    ("VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL", "6"),
    ("VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL", "7"),
    ("VK_IMAGE_LAYOUT_PREINITIALIZED", "8"),
    ("VK_IMAGE_LAYOUT_PRESENT_SRC_KHR", "1000001002"),
    // VkImageUsageFlagBits
    ("VK_IMAGE_USAGE_TRANSFER_SRC_BIT", "0x00000001"),
    ("VK_IMAGE_USAGE_TRANSFER_DST_BIT", "0x00000002"),
    ("VK_IMAGE_USAGE_SAMPLED_BIT", "0x00000004"),
    ("VK_IMAGE_USAGE_STORAGE_BIT", "0x00000008"),
    ("VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT", "0x00000010"),
    ("VK_IMAGE_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT", "0x00000020"),
    // VkImageAspectFlagBits
    ("VK_IMAGE_ASPECT_COLOR_BIT", "0x00000001"),
    ("VK_IMAGE_ASPECT_DEPTH_BIT", "0x00000002"),
    ("VK_IMAGE_ASPECT_STENCIL_BIT", "0x00000004"),
    // VkSampleCountFlagBits
    ("VK_SAMPLE_COUNT_1_BIT", "0x00000001"),
    ("VK_SAMPLE_COUNT_2_BIT", "0x00000002"),
    ("VK_SAMPLE_COUNT_4_BIT", "0x00000004"),
    ("VK_SAMPLE_COUNT_8_BIT", "0x00000008"),
    ("VK_SAMPLE_COUNT_16_BIT", "0x00000010"),
    ("VK_SAMPLE_COUNT_32_BIT", "0x00000020"),
    ("VK_SAMPLE_COUNT_64_BIT", "0x00000040"),
    // VkImageTiling
    ("VK_IMAGE_TILING_OPTIMAL", "0"),
    ("VK_IMAGE_TILING_LINEAR", "1"),
    // VkComponentSwizzle
    ("VK_COMPONENT_SWIZZLE_IDENTITY", "0"),
    ("VK_COMPONENT_SWIZZLE_ZERO", "1"),
    ("VK_COMPONENT_SWIZZLE_ONE", "2"),
    ("VK_COMPONENT_SWIZZLE_R", "3"),
    ("VK_COMPONENT_SWIZZLE_G", "4"),
    ("VK_COMPONENT_SWIZZLE_B", "5"),
    ("VK_COMPONENT_SWIZZLE_A", "6"),
];

/// Render pass / attachment enums
pub const VK_RENDERPASS_ENUMS: &[(&str, &str)] = &[
    // VkAttachmentLoadOp
    ("VK_ATTACHMENT_LOAD_OP_LOAD", "0"),
    ("VK_ATTACHMENT_LOAD_OP_CLEAR", "1"),
    ("VK_ATTACHMENT_LOAD_OP_DONT_CARE", "2"),
    // VkAttachmentStoreOp
    ("VK_ATTACHMENT_STORE_OP_STORE", "0"),
    ("VK_ATTACHMENT_STORE_OP_DONT_CARE", "1"),
    // VkSubpassContents
    ("VK_SUBPASS_CONTENTS_INLINE", "0"),
    ("VK_SUBPASS_CONTENTS_SECONDARY_COMMAND_BUFFERS", "1"),
    // VkPipelineStageFlagBits
    ("VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT", "0x00000001"),
    ("VK_PIPELINE_STAGE_DRAW_INDIRECT_BIT", "0x00000002"),
    ("VK_PIPELINE_STAGE_VERTEX_INPUT_BIT", "0x00000004"),
    ("VK_PIPELINE_STAGE_VERTEX_SHADER_BIT", "0x00000008"),
    ("VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT", "0x00000080"),
    ("VK_PIPELINE_STAGE_EARLY_FRAGMENT_TESTS_BIT", "0x00000100"),
    ("VK_PIPELINE_STAGE_LATE_FRAGMENT_TESTS_BIT", "0x00000200"),
    ("VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT", "0x00000400"),
    ("VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT", "0x00000800"),
    ("VK_PIPELINE_STAGE_TRANSFER_BIT", "0x00001000"),
    ("VK_PIPELINE_STAGE_BOTTOM_OF_PIPE_BIT", "0x00002000"),
    ("VK_PIPELINE_STAGE_ALL_GRAPHICS_BIT", "0x00008000"),
    ("VK_PIPELINE_STAGE_ALL_COMMANDS_BIT", "0x00010000"),
    // VkAccessFlagBits
    ("VK_ACCESS_INDIRECT_COMMAND_READ_BIT", "0x00000001"),
    ("VK_ACCESS_INDEX_READ_BIT", "0x00000002"),
    ("VK_ACCESS_VERTEX_ATTRIBUTE_READ_BIT", "0x00000004"),
    ("VK_ACCESS_UNIFORM_READ_BIT", "0x00000008"),
    ("VK_ACCESS_INPUT_ATTACHMENT_READ_BIT", "0x00000010"),
    ("VK_ACCESS_SHADER_READ_BIT", "0x00000020"),
    ("VK_ACCESS_SHADER_WRITE_BIT", "0x00000040"),
    ("VK_ACCESS_COLOR_ATTACHMENT_READ_BIT", "0x00000080"),
    ("VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT", "0x00000100"),
    ("VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_READ_BIT", "0x00000200"),
    ("VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_WRITE_BIT", "0x00000400"),
    ("VK_ACCESS_TRANSFER_READ_BIT", "0x00000800"),
    ("VK_ACCESS_TRANSFER_WRITE_BIT", "0x00010000"),
    ("VK_ACCESS_HOST_READ_BIT", "0x00002000"),
    ("VK_ACCESS_HOST_WRITE_BIT", "0x00004000"),
    ("VK_ACCESS_MEMORY_READ_BIT", "0x00008000"),
    ("VK_ACCESS_MEMORY_WRITE_BIT", "0x00010000"),
    // VkDependencyFlagBits
    ("VK_DEPENDENCY_BY_REGION_BIT", "0x00000001"),
];

/// Descriptor / sampler enums
pub const VK_DESCRIPTOR_ENUMS: &[(&str, &str)] = &[
    // VkDescriptorType
    ("VK_DESCRIPTOR_TYPE_SAMPLER", "0"),
    ("VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER", "1"),
    ("VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE", "2"),
    ("VK_DESCRIPTOR_TYPE_STORAGE_IMAGE", "3"),
    ("VK_DESCRIPTOR_TYPE_UNIFORM_TEXEL_BUFFER", "4"),
    ("VK_DESCRIPTOR_TYPE_STORAGE_TEXEL_BUFFER", "5"),
    ("VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER", "6"),
    ("VK_DESCRIPTOR_TYPE_STORAGE_BUFFER", "7"),
    ("VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER_DYNAMIC", "8"),
    ("VK_DESCRIPTOR_TYPE_STORAGE_BUFFER_DYNAMIC", "9"),
    ("VK_DESCRIPTOR_TYPE_INPUT_ATTACHMENT", "10"),
    // VkFilter
    ("VK_FILTER_NEAREST", "0"),
    ("VK_FILTER_LINEAR", "1"),
    // VkSamplerMipmapMode
    ("VK_SAMPLER_MIPMAP_MODE_NEAREST", "0"),
    ("VK_SAMPLER_MIPMAP_MODE_LINEAR", "1"),
    // VkSamplerAddressMode
    ("VK_SAMPLER_ADDRESS_MODE_REPEAT", "0"),
    ("VK_SAMPLER_ADDRESS_MODE_MIRRORED_REPEAT", "1"),
    ("VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE", "2"),
    ("VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_BORDER", "3"),
    // VkBorderColor
    ("VK_BORDER_COLOR_FLOAT_TRANSPARENT_BLACK", "0"),
    ("VK_BORDER_COLOR_INT_TRANSPARENT_BLACK", "1"),
    ("VK_BORDER_COLOR_FLOAT_OPAQUE_BLACK", "2"),
    ("VK_BORDER_COLOR_INT_OPAQUE_BLACK", "3"),
    ("VK_BORDER_COLOR_FLOAT_OPAQUE_WHITE", "4"),
    ("VK_BORDER_COLOR_INT_OPAQUE_WHITE", "5"),
    // VkCompareOp
    ("VK_COMPARE_OP_NEVER", "0"),
    ("VK_COMPARE_OP_LESS", "1"),
    ("VK_COMPARE_OP_EQUAL", "2"),
    ("VK_COMPARE_OP_LESS_OR_EQUAL", "3"),
    ("VK_COMPARE_OP_GREATER", "4"),
    ("VK_COMPARE_OP_NOT_EQUAL", "5"),
    ("VK_COMPARE_OP_GREATER_OR_EQUAL", "6"),
    ("VK_COMPARE_OP_ALWAYS", "7"),
];

/// Blend enums
pub const VK_BLEND_ENUMS: &[(&str, &str)] = &[
    ("VK_BLEND_FACTOR_ZERO", "0"),
    ("VK_BLEND_FACTOR_ONE", "1"),
    ("VK_BLEND_FACTOR_SRC_COLOR", "2"),
    ("VK_BLEND_FACTOR_ONE_MINUS_SRC_COLOR", "3"),
    ("VK_BLEND_FACTOR_DST_COLOR", "4"),
    ("VK_BLEND_FACTOR_ONE_MINUS_DST_COLOR", "5"),
    ("VK_BLEND_FACTOR_SRC_ALPHA", "6"),
    ("VK_BLEND_FACTOR_ONE_MINUS_SRC_ALPHA", "7"),
    ("VK_BLEND_FACTOR_DST_ALPHA", "8"),
    ("VK_BLEND_FACTOR_ONE_MINUS_DST_ALPHA", "9"),
    ("VK_BLEND_OP_ADD", "0"),
    ("VK_BLEND_OP_SUBTRACT", "1"),
    ("VK_BLEND_OP_REVERSE_SUBTRACT", "2"),
    ("VK_BLEND_OP_MIN", "3"),
    ("VK_BLEND_OP_MAX", "4"),
    ("VK_COLOR_COMPONENT_R_BIT", "0x00000001"),
    ("VK_COLOR_COMPONENT_G_BIT", "0x00000002"),
    ("VK_COLOR_COMPONENT_B_BIT", "0x00000004"),
    ("VK_COLOR_COMPONENT_A_BIT", "0x00000008"),
    // VkLogicOp
    ("VK_LOGIC_OP_CLEAR", "0"),
    ("VK_LOGIC_OP_COPY", "3"),
    ("VK_LOGIC_OP_NO_OP", "5"),
];

/// Stencil / Depth enums
pub const VK_DEPTH_STENCIL_ENUMS: &[(&str, &str)] = &[
    ("VK_STENCIL_OP_KEEP", "0"),
    ("VK_STENCIL_OP_ZERO", "1"),
    ("VK_STENCIL_OP_REPLACE", "2"),
    ("VK_STENCIL_OP_INCREMENT_AND_CLAMP", "3"),
    ("VK_STENCIL_OP_DECREMENT_AND_CLAMP", "4"),
    ("VK_STENCIL_OP_INVERT", "5"),
    ("VK_STENCIL_OP_INCREMENT_AND_WRAP", "6"),
    ("VK_STENCIL_OP_DECREMENT_AND_WRAP", "7"),
];

/// Command buffer / queue enums
pub const VK_COMMAND_ENUMS: &[(&str, &str)] = &[
    // VkCommandBufferLevel
    ("VK_COMMAND_BUFFER_LEVEL_PRIMARY", "0"),
    ("VK_COMMAND_BUFFER_LEVEL_SECONDARY", "1"),
    // VkCommandPoolCreateFlagBits
    ("VK_COMMAND_POOL_CREATE_TRANSIENT_BIT", "0x00000001"),
    ("VK_COMMAND_POOL_CREATE_RESET_COMMAND_BUFFER_BIT", "0x00000002"),
    // VkCommandBufferUsageFlagBits
    ("VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT", "0x00000001"),
    ("VK_COMMAND_BUFFER_USAGE_RENDER_PASS_CONTINUE_BIT", "0x00000002"),
    ("VK_COMMAND_BUFFER_USAGE_SIMULTANEOUS_USE_BIT", "0x00000004"),
    // VkQueueFlagBits
    ("VK_QUEUE_GRAPHICS_BIT", "0x00000001"),
    ("VK_QUEUE_COMPUTE_BIT", "0x00000002"),
    ("VK_QUEUE_TRANSFER_BIT", "0x00000004"),
    ("VK_QUEUE_SPARSE_BINDING_BIT", "0x00000008"),
    // VkFenceCreateFlagBits
    ("VK_FENCE_CREATE_SIGNALED_BIT", "0x00000001"),
    // VkIndexType
    ("VK_INDEX_TYPE_UINT16", "0"),
    ("VK_INDEX_TYPE_UINT32", "1"),
];

/// Presentation enums (KHR extensions)
pub const VK_PRESENT_ENUMS: &[(&str, &str)] = &[
    // VkPresentModeKHR
    ("VK_PRESENT_MODE_IMMEDIATE_KHR", "0"),
    ("VK_PRESENT_MODE_MAILBOX_KHR", "1"),
    ("VK_PRESENT_MODE_FIFO_KHR", "2"),
    ("VK_PRESENT_MODE_FIFO_RELAXED_KHR", "3"),
    // VkColorSpaceKHR
    ("VK_COLOR_SPACE_SRGB_NONLINEAR_KHR", "0"),
    // VkCompositeAlphaFlagBitsKHR
    ("VK_COMPOSITE_ALPHA_OPAQUE_BIT_KHR", "0x00000001"),
    ("VK_COMPOSITE_ALPHA_PRE_MULTIPLIED_BIT_KHR", "0x00000002"),
    ("VK_COMPOSITE_ALPHA_POST_MULTIPLIED_BIT_KHR", "0x00000004"),
    ("VK_COMPOSITE_ALPHA_INHERIT_BIT_KHR", "0x00000008"),
    // VkSurfaceTransformFlagBitsKHR
    ("VK_SURFACE_TRANSFORM_IDENTITY_BIT_KHR", "0x00000001"),
];

pub fn is_vk_enum(name: &str) -> bool {
    VK_RESULT_VALUES.iter().any(|(n, _)| *n == name)
        || VK_STRUCTURE_TYPES.iter().any(|(n, _)| *n == name)
        || VK_FORMAT_VALUES.iter().any(|(n, _)| *n == name)
        || VK_PIPELINE_ENUMS.iter().any(|(n, _)| *n == name)
        || VK_MEMORY_ENUMS.iter().any(|(n, _)| *n == name)
        || VK_IMAGE_ENUMS.iter().any(|(n, _)| *n == name)
        || VK_RENDERPASS_ENUMS.iter().any(|(n, _)| *n == name)
        || VK_DESCRIPTOR_ENUMS.iter().any(|(n, _)| *n == name)
        || VK_BLEND_ENUMS.iter().any(|(n, _)| *n == name)
        || VK_DEPTH_STENCIL_ENUMS.iter().any(|(n, _)| *n == name)
        || VK_COMMAND_ENUMS.iter().any(|(n, _)| *n == name)
        || VK_PRESENT_ENUMS.iter().any(|(n, _)| *n == name)
}
