//! ASM-BIB Bridge Linker for ADead-BIB
//! Merges COFF .obj files (from ASM-BIB --native) into the PE generated by codegen.
//!
//! Architecture:
//!   1. C source → codegen → code bytes (with unresolved external_calls)
//!   2. ASM-BIB .pasm → --native → .obj (COFF with exported functions)
//!   3. THIS MODULE merges both: appends .obj .text after codegen code,
//!      resolves cross-references (C calls ASM functions via rel32 patching)
//!
//! The result is a single unified .text section ready for PE wrapping.
#![allow(dead_code)]

use std::collections::HashMap;
use std::path::Path;
use std::fs;

use super::coff_reader::{CoffObject, IMAGE_REL_AMD64_REL32};

/// Result of merging codegen output with one or more COFF .obj files
#[derive(Debug)]
pub struct BridgeResult {
    /// Unified code section (codegen code + all .obj .text appended)
    pub code: Vec<u8>,
    /// Unified data section (codegen data + all .obj .data appended)
    pub data: Vec<u8>,
    /// Map of all available symbols: name → absolute offset in unified code
    pub symbol_table: HashMap<String, u32>,
    /// Unresolved externals (neither in codegen nor in any .obj)
    pub unresolved: Vec<String>,
    /// Summary for display
    pub obj_count: usize,
    pub total_asm_functions: usize,
}

/// The Bridge Linker
pub struct BridgeLinker {
    /// Code from C codegen (already generated)
    codegen_code: Vec<u8>,
    /// Data from C codegen
    codegen_data: Vec<u8>,
    /// Pending external calls from codegen: (patch_offset_in_code, function_name)
    external_calls: Vec<(usize, String)>,
    /// Function offsets from codegen (intra-module resolved calls)
    codegen_func_offsets: HashMap<String, usize>,
    /// Loaded COFF objects
    objects: Vec<CoffObject>,
}

impl BridgeLinker {
    pub fn new(
        codegen_code: Vec<u8>,
        codegen_data: Vec<u8>,
        external_calls: Vec<(usize, String)>,
        codegen_func_offsets: HashMap<String, usize>,
    ) -> Self {
        Self {
            codegen_code,
            codegen_data,
            external_calls,
            codegen_func_offsets,
            objects: Vec::new(),
        }
    }

    /// Load a COFF .obj file from disk
    pub fn load_obj(&mut self, path: &Path) -> Result<(), String> {
        let data = fs::read(path)
            .map_err(|e| format!("Cannot read '{}': {}", path.display(), e))?;
        let obj = CoffObject::parse(&data)?;
        self.objects.push(obj);
        Ok(())
    }

    /// Load a COFF .obj from raw bytes (for embedded/testing)
    pub fn load_obj_bytes(&mut self, data: &[u8]) -> Result<(), String> {
        let obj = CoffObject::parse(data)?;
        self.objects.push(obj);
        Ok(())
    }

    /// Perform the merge: append all .obj .text sections after codegen code,
    /// build unified symbol table, resolve cross-references.
    pub fn link(self) -> BridgeResult {
        let mut unified_code = self.codegen_code.clone();
        let mut unified_data = self.codegen_data.clone();
        let mut symbol_table: HashMap<String, u32> = HashMap::new();
        let mut total_asm_functions = 0usize;

        // Register codegen's own function offsets
        for (name, &offset) in &self.codegen_func_offsets {
            symbol_table.insert(name.clone(), offset as u32);
        }

        // For each loaded .obj, append its .text and register symbols
        for obj in &self.objects {
            let code_base = unified_code.len() as u32; // where this obj's .text starts
            let _data_base = unified_data.len() as u32;

            // Append .text
            if let Some(text_sec) = obj.text_section() {
                unified_code.extend_from_slice(&text_sec.data);
            }

            // Append .data
            if let Some(data_sec) = obj.data_section() {
                unified_data.extend_from_slice(&data_sec.data);
            }

            // Register exported symbols with their absolute offset
            let func_map = obj.function_map();
            for (name, (offset_in_text, _size)) in &func_map {
                symbol_table.insert(name.clone(), code_base + offset_in_text);
                total_asm_functions += 1;
            }

            // Also register any External symbols pointing to .text
            // (covers cases where function_map might miss something)
            for sym in &obj.symbols {
                if sym.storage_class == 2 && sym.section_number > 0 && !sym.name.is_empty() {
                    let sec_idx = (sym.section_number - 1) as usize;
                    if sec_idx < obj.sections.len() {
                        let sec = &obj.sections[sec_idx];
                        if sec.name == ".text" || (sec.characteristics & 0x20) != 0 {
                            // .text section — offset is code_base + sym.value
                            symbol_table.entry(sym.name.clone())
                                .or_insert(code_base + sym.value);
                        }
                    }
                }
            }

            // Resolve intra-obj relocations (REL32 within .text pointing to local labels)
            if let Some(text_sec) = obj.text_section() {
                for reloc in &text_sec.relocations {
                    if reloc.rel_type == IMAGE_REL_AMD64_REL32 {
                        let target_sym = obj.symbol_name(reloc.symbol_index);
                        if let Some(&target_offset) = symbol_table.get(target_sym) {
                            let patch_addr = (code_base + reloc.virtual_address) as usize;
                            if patch_addr + 4 <= unified_code.len() {
                                // REL32: target - (patch_addr + 4)
                                let rel = (target_offset as i32) - (patch_addr as i32) - 4;
                                unified_code[patch_addr..patch_addr + 4]
                                    .copy_from_slice(&rel.to_le_bytes());
                            }
                        }
                    }
                }
            }
        }

        // Resolve codegen's external_calls using the unified symbol table
        let mut unresolved = Vec::new();
        for (patch_offset, func_name) in &self.external_calls {
            if let Some(&target_offset) = symbol_table.get(func_name) {
                // REL32 patch: target - (patch_offset + 4)
                let rel = (target_offset as i32) - (*patch_offset as i32) - 4;
                if *patch_offset + 4 <= unified_code.len() {
                    unified_code[*patch_offset..*patch_offset + 4]
                        .copy_from_slice(&rel.to_le_bytes());
                }
            } else {
                // Still unresolved — might be an IAT import (printf, etc.)
                unresolved.push(func_name.clone());
            }
        }

        BridgeResult {
            code: unified_code,
            data: unified_data,
            symbol_table,
            unresolved,
            obj_count: self.objects.len(),
            total_asm_functions,
        }
    }
}

/// Convenience: load all .obj files from a directory
pub fn load_all_objs(dir: &Path) -> Result<Vec<CoffObject>, String> {
    let mut objects = Vec::new();
    if !dir.exists() {
        return Ok(objects);
    }
    let entries = fs::read_dir(dir)
        .map_err(|e| format!("Cannot read dir '{}': {}", dir.display(), e))?;
    for entry in entries.flatten() {
        let path = entry.path();
        if path.extension().and_then(|e| e.to_str()) == Some("obj") {
            let data = fs::read(&path)
                .map_err(|e| format!("Cannot read '{}': {}", path.display(), e))?;
            let obj = CoffObject::parse(&data)?;
            objects.push(obj);
        }
    }
    Ok(objects)
}

// === Tests ===

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_bridge_no_objs() {
        let linker = BridgeLinker::new(
            vec![0xC3], // ret
            vec![],
            vec![],
            HashMap::from([("main".to_string(), 0usize)]),
        );
        let result = linker.link();
        assert_eq!(result.code, vec![0xC3]);
        assert_eq!(result.obj_count, 0);
        assert!(result.unresolved.is_empty());
        assert_eq!(*result.symbol_table.get("main").unwrap(), 0);
    }

    #[test]
    fn test_bridge_resolves_call() {
        // Simulate: codegen has a CALL to "asm_strlen" at offset 1 (after 0xE8)
        // The call instruction is: E8 [rel32] at offset 0
        // patch_offset = 1 (the 4 bytes after E8)
        let codegen_code = vec![0xE8, 0x00, 0x00, 0x00, 0x00, 0xC3]; // call + ret
        let external_calls = vec![(1usize, "asm_strlen".to_string())];

        // Simulate a tiny .obj with asm_strlen at offset 0 in .text
        // asm_strlen: xor rax,rax; ret = 48 31 C0 C3
        let asm_code = vec![0x48, 0x31, 0xC0, 0xC3];

        // Build a minimal COFF manually
        let obj = CoffObject {
            machine: 0x8664,
            sections: vec![super::super::coff_reader::CoffSection {
                name: ".text".into(),
                characteristics: 0x60000020, // CODE | EXEC | READ
                data: asm_code,
                relocations: vec![],
            }],
            symbols: vec![super::super::coff_reader::CoffSymbol {
                name: "asm_strlen".into(),
                value: 0,
                section_number: 1,
                storage_class: 2, // External
                num_aux: 0,
            }],
            exports: vec!["asm_strlen".into()],
        };

        let mut linker = BridgeLinker::new(
            codegen_code,
            vec![],
            external_calls,
            HashMap::from([("main".to_string(), 0usize)]),
        );
        linker.objects.push(obj);

        let result = linker.link();

        // asm_strlen should be at offset 6 (after codegen's 6 bytes)
        assert_eq!(*result.symbol_table.get("asm_strlen").unwrap(), 6);

        // The call at offset 1 should now have rel32 = 6 - (1 + 4) = 1
        let rel32 = i32::from_le_bytes([result.code[1], result.code[2], result.code[3], result.code[4]]);
        assert_eq!(rel32, 1); // target(6) - patch_end(5) = 1

        assert!(result.unresolved.is_empty());
        assert_eq!(result.total_asm_functions, 1);
    }

    #[test]
    fn test_bridge_unresolved_stays() {
        let codegen_code = vec![0xE8, 0x00, 0x00, 0x00, 0x00];
        let external_calls = vec![(1usize, "printf".to_string())];

        let linker = BridgeLinker::new(
            codegen_code,
            vec![],
            external_calls,
            HashMap::new(),
        );
        let result = linker.link();

        // printf not in any .obj → stays unresolved
        assert_eq!(result.unresolved, vec!["printf"]);
    }
}
