//! COFF .obj Reader for ADead-BIB
//! Parses Microsoft PE/COFF object files generated by ASM-BIB (--native)
//! Extracts: sections (.text, .data), symbols (exported functions), relocations
//!
//! Pipeline: ASM-BIB .pasm → --native → .obj (COFF) → THIS READER → merge with PE
#![allow(dead_code)]

use std::collections::HashMap;

// === COFF Constants ===
pub const IMAGE_FILE_MACHINE_AMD64: u16 = 0x8664;
pub const IMAGE_FILE_MACHINE_I386: u16 = 0x014C;

// Relocation types (AMD64)
pub const IMAGE_REL_AMD64_ABSOLUTE: u16 = 0x0000;
pub const IMAGE_REL_AMD64_ADDR64: u16 = 0x0001;
pub const IMAGE_REL_AMD64_ADDR32: u16 = 0x0002;
pub const IMAGE_REL_AMD64_ADDR32NB: u16 = 0x0003;
pub const IMAGE_REL_AMD64_REL32: u16 = 0x0004;

// Symbol storage classes
pub const IMAGE_SYM_CLASS_EXTERNAL: u8 = 2;
pub const IMAGE_SYM_CLASS_STATIC: u8 = 3;
pub const IMAGE_SYM_CLASS_FUNCTION: u8 = 101;

// Section characteristics
pub const IMAGE_SCN_CNT_CODE: u32 = 0x00000020;
pub const IMAGE_SCN_CNT_INITIALIZED_DATA: u32 = 0x00000040;
pub const IMAGE_SCN_MEM_EXECUTE: u32 = 0x20000000;
pub const IMAGE_SCN_MEM_READ: u32 = 0x40000000;

// === Parsed Structures ===

#[derive(Debug, Clone)]
pub struct CoffObject {
    pub machine: u16,
    pub sections: Vec<CoffSection>,
    pub symbols: Vec<CoffSymbol>,
    pub exports: Vec<String>,  // exported function names (External, section > 0)
}

#[derive(Debug, Clone)]
pub struct CoffSection {
    pub name: String,
    pub characteristics: u32,
    pub data: Vec<u8>,
    pub relocations: Vec<CoffRelocation>,
}

#[derive(Debug, Clone)]
pub struct CoffRelocation {
    pub virtual_address: u32,
    pub symbol_index: u32,
    pub rel_type: u16,
}

#[derive(Debug, Clone)]
pub struct CoffSymbol {
    pub name: String,
    pub value: u32,        // offset within section
    pub section_number: i16,  // 1-based, 0 = undefined (external ref)
    pub storage_class: u8,
    pub num_aux: u8,
}

impl CoffObject {
    /// Parse a COFF .obj file from raw bytes
    pub fn parse(data: &[u8]) -> Result<Self, String> {
        if data.len() < 20 {
            return Err("COFF: file too small (< 20 bytes)".into());
        }

        let machine = u16_le(data, 0);
        let num_sections = u16_le(data, 2) as usize;
        let sym_table_ptr = u32_le(data, 8) as usize;
        let num_symbols = u32_le(data, 12) as usize;

        // Validate machine type
        if machine != IMAGE_FILE_MACHINE_AMD64 && machine != IMAGE_FILE_MACHINE_I386 {
            return Err(format!("COFF: unknown machine type 0x{:04X}", machine));
        }

        // Parse string table (located after symbol table)
        let str_table_offset = sym_table_ptr + num_symbols * 18;
        let string_table = if str_table_offset + 4 <= data.len() {
            let str_size = u32_le(data, str_table_offset) as usize;
            let end = (str_table_offset + str_size).min(data.len());
            data[str_table_offset..end].to_vec()
        } else {
            vec![0, 0, 0, 4] // empty string table (size = 4)
        };

        // Parse symbols
        let mut symbols = Vec::with_capacity(num_symbols);
        let mut skip_aux = 0u8;
        for i in 0..num_symbols {
            let off = sym_table_ptr + i * 18;
            if off + 18 > data.len() { break; }

            if skip_aux > 0 {
                skip_aux -= 1;
                // Aux record — placeholder
                symbols.push(CoffSymbol {
                    name: String::new(),
                    value: 0,
                    section_number: 0,
                    storage_class: 0,
                    num_aux: 0,
                });
                continue;
            }

            let name = read_symbol_name(&data[off..off + 8], &string_table);
            let value = u32_le(data, off + 8);
            let section_number = i16_le(data, off + 12);
            let storage_class = data[off + 16];
            let num_aux = data[off + 17];

            symbols.push(CoffSymbol { name, value, section_number, storage_class, num_aux });
            skip_aux = num_aux;
        }

        // Parse sections
        let mut sections = Vec::with_capacity(num_sections);
        for i in 0..num_sections {
            let sh_off = 20 + i * 40;
            if sh_off + 40 > data.len() { break; }

            let sec_name = read_section_name(&data[sh_off..sh_off + 8], &string_table);
            let raw_size = u32_le(data, sh_off + 16) as usize;
            let raw_ptr = u32_le(data, sh_off + 20) as usize;
            let reloc_ptr = u32_le(data, sh_off + 24) as usize;
            let num_relocs = u16_le(data, sh_off + 32) as usize;
            let characteristics = u32_le(data, sh_off + 36);

            // Read section raw data
            let sec_data = if raw_ptr > 0 && raw_ptr + raw_size <= data.len() {
                data[raw_ptr..raw_ptr + raw_size].to_vec()
            } else {
                vec![0u8; raw_size]
            };

            // Read relocations
            let mut relocs = Vec::with_capacity(num_relocs);
            for r in 0..num_relocs {
                let roff = reloc_ptr + r * 10;
                if roff + 10 > data.len() { break; }
                relocs.push(CoffRelocation {
                    virtual_address: u32_le(data, roff),
                    symbol_index: u32_le(data, roff + 4),
                    rel_type: u16_le(data, roff + 8),
                });
            }

            sections.push(CoffSection {
                name: sec_name,
                characteristics,
                data: sec_data,
                relocations: relocs,
            });
        }

        // Collect exported symbols (External class, defined in a section)
        let exports: Vec<String> = symbols.iter()
            .filter(|s| s.storage_class == IMAGE_SYM_CLASS_EXTERNAL && s.section_number > 0)
            .filter(|s| !s.name.is_empty())
            .map(|s| s.name.clone())
            .collect();

        Ok(CoffObject { machine, sections, symbols, exports })
    }

    /// Get the .text section (code)
    pub fn text_section(&self) -> Option<&CoffSection> {
        self.sections.iter().find(|s| s.name == ".text" || (s.characteristics & IMAGE_SCN_CNT_CODE) != 0)
    }

    /// Get the .data section
    pub fn data_section(&self) -> Option<&CoffSection> {
        self.sections.iter().find(|s| s.name == ".data")
    }

    /// Build a map: function_name → (offset_in_text, size)
    /// Uses symbol values within .text to determine function boundaries
    pub fn function_map(&self) -> HashMap<String, (u32, u32)> {
        let text_sec_idx = self.sections.iter().position(|s| 
            s.name == ".text" || (s.characteristics & IMAGE_SCN_CNT_CODE) != 0
        );
        let text_sec_num = match text_sec_idx {
            Some(idx) => (idx + 1) as i16, // COFF sections are 1-based
            None => return HashMap::new(),
        };
        let text_size = self.sections.get(text_sec_idx.unwrap())
            .map(|s| s.data.len() as u32)
            .unwrap_or(0);

        // Collect function starts sorted by offset
        let mut func_starts: Vec<(&str, u32)> = self.symbols.iter()
            .filter(|s| s.storage_class == IMAGE_SYM_CLASS_EXTERNAL && s.section_number == text_sec_num)
            .filter(|s| !s.name.is_empty())
            .map(|s| (s.name.as_str(), s.value))
            .collect();
        func_starts.sort_by_key(|&(_, off)| off);

        let mut map = HashMap::new();
        for i in 0..func_starts.len() {
            let (name, start) = func_starts[i];
            let end = if i + 1 < func_starts.len() {
                func_starts[i + 1].1
            } else {
                text_size
            };
            map.insert(name.to_string(), (start, end - start));
        }
        map
    }

    /// Get symbol name by index (for relocation resolution)
    pub fn symbol_name(&self, idx: u32) -> &str {
        self.symbols.get(idx as usize).map(|s| s.name.as_str()).unwrap_or("")
    }

    /// Summary for step mode display
    pub fn summary(&self) -> String {
        format!(
            "COFF x{}: {} sections, {} symbols, {} exports [{}]",
            if self.machine == IMAGE_FILE_MACHINE_AMD64 { "64" } else { "32" },
            self.sections.len(),
            self.symbols.iter().filter(|s| !s.name.is_empty()).count(),
            self.exports.len(),
            self.exports.join(", ")
        )
    }
}

// === Helpers ===

fn u16_le(data: &[u8], off: usize) -> u16 {
    u16::from_le_bytes([data[off], data[off + 1]])
}

fn u32_le(data: &[u8], off: usize) -> u32 {
    u32::from_le_bytes([data[off], data[off + 1], data[off + 2], data[off + 3]])
}

fn i16_le(data: &[u8], off: usize) -> i16 {
    i16::from_le_bytes([data[off], data[off + 1]])
}

fn read_symbol_name(name_bytes: &[u8], string_table: &[u8]) -> String {
    // If first 4 bytes are zero → long name via string table
    if name_bytes[0] == 0 && name_bytes[1] == 0 && name_bytes[2] == 0 && name_bytes[3] == 0 {
        let offset = u32::from_le_bytes([name_bytes[4], name_bytes[5], name_bytes[6], name_bytes[7]]) as usize;
        if offset < string_table.len() {
            let end = string_table[offset..].iter().position(|&b| b == 0).unwrap_or(string_table.len() - offset);
            return String::from_utf8_lossy(&string_table[offset..offset + end]).to_string();
        }
        return String::new();
    }
    // Short name: up to 8 bytes
    let end = name_bytes.iter().position(|&b| b == 0).unwrap_or(8);
    String::from_utf8_lossy(&name_bytes[..end]).to_string()
}

fn read_section_name(name_bytes: &[u8], string_table: &[u8]) -> String {
    // Names starting with '/' use decimal offset into string table
    if name_bytes[0] == b'/' {
        let offset_str = String::from_utf8_lossy(&name_bytes[1..]).trim_end_matches('\0').to_string();
        if let Ok(offset) = offset_str.trim().parse::<usize>() {
            if offset < string_table.len() {
                let end = string_table[offset..].iter().position(|&b| b == 0).unwrap_or(string_table.len() - offset);
                return String::from_utf8_lossy(&string_table[offset..offset + end]).to_string();
            }
        }
    }
    let end = name_bytes.iter().position(|&b| b == 0).unwrap_or(8);
    String::from_utf8_lossy(&name_bytes[..end]).to_string()
}

// === Tests ===

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_reject_too_small() {
        let data = vec![0u8; 10];
        assert!(CoffObject::parse(&data).is_err());
    }

    #[test]
    fn test_parse_minimal_coff() {
        // Minimal valid COFF: header only, 0 sections, 0 symbols
        let mut data = vec![0u8; 20];
        data[0] = 0x64; data[1] = 0x86; // AMD64
        // num_sections = 0, sym_table_ptr = 20, num_symbols = 0
        data[8] = 20; // sym_table_ptr points right after header
        let obj = CoffObject::parse(&data).unwrap();
        assert_eq!(obj.machine, IMAGE_FILE_MACHINE_AMD64);
        assert_eq!(obj.sections.len(), 0);
        assert_eq!(obj.exports.len(), 0);
    }

    #[test]
    fn test_summary_format() {
        let obj = CoffObject {
            machine: IMAGE_FILE_MACHINE_AMD64,
            sections: vec![],
            symbols: vec![],
            exports: vec!["asm_strlen".into(), "asm_memcpy".into()],
        };
        let s = obj.summary();
        assert!(s.contains("x64"));
        assert!(s.contains("asm_strlen"));
    }
}
