// ============================================================
// fastos_com.rs — COM/OLE Runtime Support
// ============================================================
// COM (Component Object Model) — Foundation for DirectX
// All DirectX versions (9-12), DirectWrite, Direct2D use COM
// Must be initialized before any DX call
// ============================================================

/// COM lifecycle and object creation functions (ole32.dll)
pub const COM_FUNCTIONS: &[&str] = &[
    "CoInitialize", "CoInitializeEx", "CoUninitialize",
    "CoCreateInstance", "CoGetClassObject",
    "CoTaskMemAlloc", "CoTaskMemRealloc", "CoTaskMemFree",
    "CoMarshalInterThreadInterfaceInStream",
    "CoGetInterfaceAndReleaseStream",
    "StringFromCLSID", "CLSIDFromString",
    "StringFromGUID2", "IIDFromString",
    "StringFromIID",
    "CoRegisterClassObject", "CoRevokeClassObject",
    "PropVariantClear",
];

/// OLE Automation functions (oleaut32.dll)
pub const OLEAUT_FUNCTIONS: &[&str] = &[
    "SysAllocString", "SysAllocStringLen",
    "SysFreeString", "SysStringLen", "SysStringByteLen",
    "SysReAllocString", "SysReAllocStringLen",
    "VariantInit", "VariantClear", "VariantCopy",
    "VariantChangeType", "VariantChangeTypeEx",
    "SafeArrayCreate", "SafeArrayCreateVector",
    "SafeArrayDestroy", "SafeArrayAccessData", "SafeArrayUnaccessData",
    "SafeArrayGetDim", "SafeArrayGetLBound", "SafeArrayGetUBound",
    "SafeArrayGetElement", "SafeArrayPutElement",
    "SafeArrayLock", "SafeArrayUnlock",
    "RegisterTypeLib", "LoadTypeLib", "LoadRegTypeLib",
    "CreateDispTypeInfo", "CreateStdDispatch",
    "DispGetParam", "DispInvoke",
];

/// COM interface method names for IUnknown (base of everything)
pub const IUNKNOWN_METHODS: &[&str] = &[
    "QueryInterface", "AddRef", "Release",
];

/// COM interface method names for IClassFactory
pub const ICLASSFACTORY_METHODS: &[&str] = &[
    "CreateInstance", "LockServer",
];

/// COM HRESULTs
pub const COM_HRESULTS: &[(&str, &str)] = &[
    ("S_OK", "0x00000000"),
    ("S_FALSE", "0x00000001"),
    ("E_NOTIMPL", "0x80004001"),
    ("E_NOINTERFACE", "0x80004002"),
    ("E_POINTER", "0x80004003"),
    ("E_ABORT", "0x80004004"),
    ("E_FAIL", "0x80004005"),
    ("E_UNEXPECTED", "0x8000FFFF"),
    ("E_ACCESSDENIED", "0x80070005"),
    ("E_HANDLE", "0x80070006"),
    ("E_OUTOFMEMORY", "0x8007000E"),
    ("E_INVALIDARG", "0x80070057"),
    ("CLASS_E_NOAGGREGATION", "0x80040110"),
    ("CLASS_E_CLASSNOTAVAILABLE", "0x80040111"),
    ("REGDB_E_CLASSNOTREG", "0x80040154"),
];

/// COM threading models
pub const COM_THREADING: &[(&str, &str)] = &[
    ("COINIT_APARTMENTTHREADED", "0x2"),
    ("COINIT_MULTITHREADED", "0x0"),
    ("COINIT_DISABLE_OLE1DDE", "0x4"),
    ("COINIT_SPEED_OVER_MEMORY", "0x8"),
    ("CLSCTX_INPROC_SERVER", "0x1"),
    ("CLSCTX_INPROC_HANDLER", "0x2"),
    ("CLSCTX_LOCAL_SERVER", "0x4"),
    ("CLSCTX_ALL", "0x17"),
];

/// Well-known COM GUIDs needed for DirectX
pub const COM_GUIDS: &[(&str, &str)] = &[
    ("IID_IUnknown", "{00000000-0000-0000-C000-000000000046}"),
    ("IID_IClassFactory", "{00000001-0000-0000-C000-000000000046}"),
    ("IID_IMarshal", "{00000003-0000-0000-C000-000000000046}"),
    ("IID_IDispatch", "{00020400-0000-0000-C000-000000000046}"),
];

pub fn is_com_symbol(name: &str) -> bool {
    COM_FUNCTIONS.contains(&name)
        || OLEAUT_FUNCTIONS.contains(&name)
        || IUNKNOWN_METHODS.contains(&name)
        || COM_HRESULTS.iter().any(|(n, _)| *n == name)
        || COM_THREADING.iter().any(|(n, _)| *n == name)
        || COM_GUIDS.iter().any(|(n, _)| *n == name)
}

/// Generate the COM types header content
pub fn generate_com_types_h() -> String {
    let mut out = String::with_capacity(8192);
    out.push_str("/* com_types.h — Generated by ADead-BIB */\n");
    out.push_str("#ifndef _ADEAD_COM_TYPES_H\n#define _ADEAD_COM_TYPES_H\n\n");

    out.push_str("#include <stdint.h>\n\n");

    // GUID struct
    out.push_str("typedef struct _GUID {\n");
    out.push_str("    uint32_t Data1;\n");
    out.push_str("    uint16_t Data2;\n");
    out.push_str("    uint16_t Data3;\n");
    out.push_str("    uint8_t  Data4[8];\n");
    out.push_str("} GUID, IID, CLSID, FMTID;\n\n");

    out.push_str("typedef GUID *LPGUID, *LPIID, *LPCLSID;\n");
    out.push_str("typedef const GUID *REFGUID, *REFIID, *REFCLSID;\n\n");

    // HRESULT
    out.push_str("typedef long HRESULT;\n");
    for (name, val) in COM_HRESULTS {
        out.push_str(&format!("#define {} ((HRESULT){})\n", name, val));
    }
    out.push_str("\n#define SUCCEEDED(hr) (((HRESULT)(hr)) >= 0)\n");
    out.push_str("#define FAILED(hr)    (((HRESULT)(hr)) < 0)\n\n");

    // COINIT
    for (name, val) in COM_THREADING {
        out.push_str(&format!("#define {} {}\n", name, val));
    }

    // IUnknown vtable
    out.push_str("\n/* IUnknown — base interface for all COM objects */\n");
    out.push_str("typedef struct IUnknownVtbl {\n");
    out.push_str("    HRESULT (*QueryInterface)(void *This, const IID *riid, void **ppvObject);\n");
    out.push_str("    unsigned long (*AddRef)(void *This);\n");
    out.push_str("    unsigned long (*Release)(void *This);\n");
    out.push_str("} IUnknownVtbl;\n\n");

    out.push_str("typedef struct IUnknown {\n");
    out.push_str("    IUnknownVtbl *lpVtbl;\n");
    out.push_str("} IUnknown;\n\n");

    // VARIANT
    out.push_str("/* VARIANT — OLE Automation universal type */\n");
    out.push_str("typedef unsigned short VARTYPE;\n");
    out.push_str("#define VT_EMPTY 0\n#define VT_NULL 1\n#define VT_I2 2\n#define VT_I4 3\n");
    out.push_str("#define VT_R4 4\n#define VT_R8 5\n#define VT_BSTR 8\n#define VT_BOOL 11\n");
    out.push_str("#define VT_VARIANT 12\n#define VT_UNKNOWN 13\n#define VT_I1 16\n#define VT_UI1 17\n");
    out.push_str("#define VT_UI2 18\n#define VT_UI4 19\n#define VT_I8 20\n#define VT_UI8 21\n");
    out.push_str("#define VT_INT 22\n#define VT_UINT 23\n#define VT_LPSTR 30\n#define VT_LPWSTR 31\n\n");

    // BSTR
    out.push_str("typedef wchar_t *BSTR;\n\n");

    // SAFEARRAY
    out.push_str("typedef struct tagSAFEARRAYBOUND {\n");
    out.push_str("    unsigned long cElements;\n");
    out.push_str("    long lLbound;\n");
    out.push_str("} SAFEARRAYBOUND;\n\n");

    out.push_str("typedef struct tagSAFEARRAY {\n");
    out.push_str("    unsigned short cDims;\n");
    out.push_str("    unsigned short fFeatures;\n");
    out.push_str("    unsigned long cbElements;\n");
    out.push_str("    unsigned long cLocks;\n");
    out.push_str("    void *pvData;\n");
    out.push_str("    SAFEARRAYBOUND rgsabound[1];\n");
    out.push_str("} SAFEARRAY;\n\n");

    out.push_str("#endif /* _ADEAD_COM_TYPES_H */\n");
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_com_symbol_recognition() {
        assert!(is_com_symbol("CoInitializeEx"));
        assert!(is_com_symbol("CoCreateInstance"));
        assert!(is_com_symbol("QueryInterface"));
        assert!(is_com_symbol("S_OK"));
        assert!(is_com_symbol("E_FAIL"));
        assert!(is_com_symbol("CLSCTX_ALL"));
        assert!(!is_com_symbol("printf"));
    }

    #[test]
    fn test_generate_com_types() {
        let h = generate_com_types_h();
        assert!(h.contains("GUID"));
        assert!(h.contains("IUnknown"));
        assert!(h.contains("HRESULT"));
        assert!(h.contains("SUCCEEDED"));
        assert!(h.contains("SAFEARRAY"));
    }
}
