// ============================================================
// Header Resolver — Automatic header resolution sin CMake
// ============================================================
// Busca header_main.h, resuelve includes automaticamente.
// Sin CMake. Sin Makefile. Sin flags raros.
// ============================================================

use std::collections::HashMap;
use std::path::{Path, PathBuf};

/// Resuelve headers automaticamente sin CMake/Makefile
pub struct HeaderResolver {
    /// Directorios de busqueda para headers
    search_paths: Vec<PathBuf>,
    /// Cache de headers ya resueltos (path -> contenido)
    resolved_cache: HashMap<String, String>,
    /// Headers ya incluidos (para evitar doble inclusion)
    included: HashMap<String, bool>,
}

impl HeaderResolver {
    pub fn new() -> Self {
        Self {
            search_paths: Vec::new(),
            resolved_cache: HashMap::new(),
            included: HashMap::new(),
        }
    }

    /// Agrega directorio de busqueda
    pub fn add_search_path(&mut self, path: PathBuf) {
        if !self.search_paths.contains(&path) {
            self.search_paths.push(path);
        }
    }

    /// Configura paths default: directorio del archivo fuente + include/
    pub fn setup_default_paths(&mut self, source_file: &Path) {
        if let Some(parent) = source_file.parent() {
            self.add_search_path(parent.to_path_buf());
            self.add_search_path(parent.join("include"));
            self.add_search_path(parent.join("src"));
        }
    }

    /// Resuelve un #include "header.h" — busca en search_paths
    pub fn resolve(&mut self, header_name: &str) -> Result<String, ResolverError> {
        // Skip si ya fue incluido (include guard automatico)
        if self.included.contains_key(header_name) {
            return Ok(String::new());
        }

        // header_main.h es especial — carga todo fastos
        if header_name == "header_main.h" {
            self.included.insert(header_name.to_string(), true);
            return Ok(self.generate_header_main());
        }

        // Buscar en cache
        if let Some(content) = self.resolved_cache.get(header_name) {
            return Ok(content.clone());
        }

        // Buscar en search paths
        for search_path in &self.search_paths {
            let full_path = search_path.join(header_name);
            if full_path.exists() {
                match std::fs::read_to_string(&full_path) {
                    Ok(content) => {
                        self.included.insert(header_name.to_string(), true);
                        self.resolved_cache
                            .insert(header_name.to_string(), content.clone());
                        return Ok(content);
                    }
                    Err(_) => continue,
                }
            }
        }

        Err(ResolverError::HeaderNotFound(header_name.to_string()))
    }

    /// Genera el contenido de header_main.h — todo FastOS en 1 linea
    fn generate_header_main(&self) -> String {
        // header_main.h incluye todo el ecosystem FastOS
        let mut content = String::new();
        content.push_str("// header_main.h — Generated by ADead-BIB\n");
        content.push_str("// Una sola linea. Todo disponible. Sin CMake.\n\n");
        content.push_str("#ifndef HEADER_MAIN_H\n");
        content.push_str("#define HEADER_MAIN_H\n\n");
        content.push_str("// fastos_types.h — u8, u16, u32, u64, i8, i16, i32, i64, bool\n");
        content.push_str("// fastos_memory.h — fastos_alloc(), fastos_free(), fastos_realloc()\n");
        content.push_str("// fastos_io.h — fastos_print(), fastos_read(), fastos_file_open()\n");
        content.push_str("// fastos_math.h — Vec2, Vec3, Vec4, Mat4x4, fastos_sqrt()\n");
        content
            .push_str("// fastos_string.h — fastos_strlen(), fastos_strcmp(), fastos_strcpy()\n");
        content.push_str("// fastos_thread.h — fastos_thread_create(), fastos_mutex()\n");
        content.push_str("// fastos_window.h — fastos_create_window(), fastos_draw()\n");
        content.push_str("// fastos_network.h — fastos_connect(), fastos_send(), fastos_recv()\n");
        content.push_str("// fastos_time.h — fastos_now(), fastos_sleep(), fastos_delta()\n");
        content
            .push_str("// fastos_debug.h — fastos_assert(), fastos_log(), fastos_breakpoint()\n\n");
        content.push_str("#endif // HEADER_MAIN_H\n");
        content
    }

    /// Retorna true si un header ya fue incluido
    pub fn is_included(&self, header_name: &str) -> bool {
        self.included.contains_key(header_name)
    }

    /// Retorna cuantos headers fueron resueltos
    pub fn resolved_count(&self) -> usize {
        self.included.len()
    }
}

impl Default for HeaderResolver {
    fn default() -> Self {
        Self::new()
    }
}

#[derive(Debug)]
pub enum ResolverError {
    HeaderNotFound(String),
    ReadError(String),
}

impl std::fmt::Display for ResolverError {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            ResolverError::HeaderNotFound(h) => write!(f, "Header not found: '{}'", h),
            ResolverError::ReadError(e) => write!(f, "Read error: {}", e),
        }
    }
}

impl std::error::Error for ResolverError {}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_resolver_creation() {
        let resolver = HeaderResolver::new();
        assert_eq!(resolver.resolved_count(), 0);
    }

    #[test]
    fn test_header_main_resolution() {
        let mut resolver = HeaderResolver::new();
        let result = resolver.resolve("header_main.h");
        assert!(result.is_ok());
        assert!(result.unwrap().contains("HEADER_MAIN_H"));
    }

    #[test]
    fn test_double_include_guard() {
        let mut resolver = HeaderResolver::new();
        let _ = resolver.resolve("header_main.h");
        let second = resolver.resolve("header_main.h");
        assert!(second.is_ok());
        assert!(second.unwrap().is_empty()); // No duplicado
    }
}
