// ============================================================
// CUDead-BIB — PTX Emitter
// ============================================================
// Genera código PTX directamente desde IR
// Sin NVCC — Sin runtime oficial de NVIDIA
// ============================================================

use super::ir::{CmpOp, CudeadIR, CudeadOp, IrConst, IrType, KernelIR};
use super::primitives::KernelType;
use super::GpuArch;

/// PTX Emitter — generates PTX assembly from CUDead IR
pub struct PtxEmitter {
    arch: GpuArch,
    output: String,
    indent: usize,
}

impl PtxEmitter {
    pub fn new(arch: GpuArch) -> Self {
        Self {
            arch,
            output: String::new(),
            indent: 0,
        }
    }

    fn emit_line(&mut self, line: &str) {
        for _ in 0..self.indent {
            self.output.push('\t');
        }
        self.output.push_str(line);
        self.output.push('\n');
    }

    pub fn emit(&self, ir: &CudeadIR) -> Result<String, super::CudeadError> {
        let mut emitter = PtxEmitter::new(self.arch);
        emitter.emit_header();

        // Emit device functions first
        for func in &ir.device_functions {
            emitter.emit_function(func)?;
        }

        // Emit kernels
        for kernel in &ir.kernels {
            emitter.emit_kernel(kernel)?;
        }

        Ok(emitter.output)
    }

    fn emit_header(&mut self) {
        let (major, minor) = self.arch.sm_version();

        self.emit_line("// ============================================================");
        self.emit_line("// Generated by CUDead-BIB — GPU Compiler Nativo");
        self.emit_line("// Sin NVCC — Sin runtime oficial — Binary Is Binary");
        self.emit_line("// ============================================================");
        self.emit_line("");
        self.emit_line(&format!(".version 7.8"));
        self.emit_line(&format!(".target sm_{}{}", major, minor));
        self.emit_line(".address_size 64");
        self.emit_line("");
    }

    fn emit_kernel(&mut self, kernel: &KernelIR) -> Result<(), super::CudeadError> {
        // Kernel entry point
        self.emit_line(&format!(".visible .entry {}(", kernel.name));
        self.indent += 1;

        // Parameters
        for (i, (name, ty, is_ptr)) in kernel.params.iter().enumerate() {
            let ptx_type = if *is_ptr { ".u64" } else { ty.to_ptx() };
            let comma = if i < kernel.params.len() - 1 { "," } else { "" };
            self.emit_line(&format!(".param {} {}_{}{}", ptx_type, name, i, comma));
        }

        self.indent -= 1;
        self.emit_line(")");
        self.emit_line("{");
        self.indent += 1;

        // Register declarations
        self.emit_line("// Register declarations");
        self.emit_line(&format!(".reg .s32 %r<{}>;", kernel.next_reg.max(32)));
        self.emit_line(&format!(".reg .s64 %rd<{}>;", kernel.next_reg.max(16)));
        self.emit_line(&format!(".reg .f32 %f<{}>;", kernel.next_reg.max(16)));
        self.emit_line(&format!(".reg .f64 %fd<{}>;", kernel.next_reg.max(8)));
        self.emit_line(".reg .pred %p<8>;");
        self.emit_line("");

        // Shared memory (if any)
        if kernel.shared_memory > 0 {
            self.emit_line(&format!(
                ".shared .align 16 .b8 shared_mem[{}];",
                kernel.shared_memory
            ));
            self.emit_line("");
        }

        // Load parameters
        self.emit_line("// Load parameters");
        for (i, (name, ty, is_ptr)) in kernel.params.iter().enumerate() {
            if *is_ptr {
                self.emit_line(&format!("ld.param.u64 %rd{}, [{}_{});", i, name, i));
            } else {
                let ptx_type = ty.to_ptx();
                let reg_prefix = match ty {
                    IrType::F32 => "%f",
                    IrType::F64 => "%fd",
                    IrType::I64 | IrType::U64 | IrType::Ptr => "%rd",
                    _ => "%r",
                };
                self.emit_line(&format!(
                    "ld.param{} {}{}, [{}_{});",
                    ptx_type, reg_prefix, i, name, i
                ));
            }
        }
        self.emit_line("");

        // Emit basic blocks
        for block in &kernel.blocks {
            if block.id > 0 {
                self.emit_line(&format!("BB{}:", block.id));
            }

            for op in &block.ops {
                self.emit_op(op)?;
            }
        }

        self.indent -= 1;
        self.emit_line("}");
        self.emit_line("");

        Ok(())
    }

    fn emit_function(&mut self, func: &KernelIR) -> Result<(), super::CudeadError> {
        // Device function
        self.emit_line(&format!(".func {}(", func.name));
        self.indent += 1;

        for (i, (name, ty, is_ptr)) in func.params.iter().enumerate() {
            let ptx_type = if *is_ptr { ".u64" } else { ty.to_ptx() };
            let comma = if i < func.params.len() - 1 { "," } else { "" };
            self.emit_line(&format!(".param {} {}_{}{}", ptx_type, name, i, comma));
        }

        self.indent -= 1;
        self.emit_line(")");
        self.emit_line("{");
        self.indent += 1;

        // Register declarations
        self.emit_line(&format!(".reg .s32 %r<{}>;", func.next_reg.max(16)));
        self.emit_line(&format!(".reg .s64 %rd<{}>;", func.next_reg.max(8)));
        self.emit_line(&format!(".reg .f32 %f<{}>;", func.next_reg.max(8)));
        self.emit_line(".reg .pred %p<4>;");
        self.emit_line("");

        // Emit operations
        for block in &func.blocks {
            for op in &block.ops {
                self.emit_op(op)?;
            }
        }

        self.indent -= 1;
        self.emit_line("}");
        self.emit_line("");

        Ok(())
    }

    fn emit_op(&mut self, op: &CudeadOp) -> Result<(), super::CudeadError> {
        match op {
            // Arithmetic
            CudeadOp::Add { dst, src1, src2, ty } => {
                let (prefix, suffix) = self.reg_info(ty);
                self.emit_line(&format!(
                    "add{} {}{}, {}{}, {}{};",
                    suffix, prefix, dst, prefix, src1, prefix, src2
                ));
            }
            CudeadOp::Sub { dst, src1, src2, ty } => {
                let (prefix, suffix) = self.reg_info(ty);
                self.emit_line(&format!(
                    "sub{} {}{}, {}{}, {}{};",
                    suffix, prefix, dst, prefix, src1, prefix, src2
                ));
            }
            CudeadOp::Mul { dst, src1, src2, ty } => {
                let (prefix, suffix) = self.reg_info(ty);
                let mul_op = if matches!(ty, IrType::I32 | IrType::I64) {
                    "mul.lo"
                } else {
                    "mul"
                };
                self.emit_line(&format!(
                    "{}{} {}{}, {}{}, {}{};",
                    mul_op, suffix, prefix, dst, prefix, src1, prefix, src2
                ));
            }
            CudeadOp::Div { dst, src1, src2, ty } => {
                let (prefix, suffix) = self.reg_info(ty);
                self.emit_line(&format!(
                    "div{} {}{}, {}{}, {}{};",
                    suffix, prefix, dst, prefix, src1, prefix, src2
                ));
            }
            CudeadOp::Fma {
                dst,
                src1,
                src2,
                src3,
                ty,
            } => {
                let (prefix, suffix) = self.reg_info(ty);
                self.emit_line(&format!(
                    "fma.rn{} {}{}, {}{}, {}{}, {}{};",
                    suffix, prefix, dst, prefix, src1, prefix, src2, prefix, src3
                ));
            }
            CudeadOp::Neg { dst, src, ty } => {
                let (prefix, suffix) = self.reg_info(ty);
                self.emit_line(&format!("neg{} {}{}, {}{};", suffix, prefix, dst, prefix, src));
            }

            // Memory
            CudeadOp::Load { dst, addr, ty } => {
                let (prefix, suffix) = self.reg_info(ty);
                self.emit_line(&format!(
                    "ld.global{} {}{}, [%rd{}];",
                    suffix, prefix, dst, addr
                ));
            }
            CudeadOp::Store { addr, src, ty } => {
                let (prefix, suffix) = self.reg_info(ty);
                self.emit_line(&format!(
                    "st.global{} [%rd{}], {}{};",
                    suffix, addr, prefix, src
                ));
            }
            CudeadOp::LoadShared { dst, addr, ty } => {
                let (prefix, suffix) = self.reg_info(ty);
                self.emit_line(&format!(
                    "ld.shared{} {}{}, [%r{}];",
                    suffix, prefix, dst, addr
                ));
            }
            CudeadOp::StoreShared { addr, src, ty } => {
                let (prefix, suffix) = self.reg_info(ty);
                self.emit_line(&format!(
                    "st.shared{} [%r{}], {}{};",
                    suffix, addr, prefix, src
                ));
            }

            // Thread indexing
            CudeadOp::ThreadIdxX { dst } => {
                self.emit_line(&format!("mov.u32 %r{}, %tid.x;", dst));
            }
            CudeadOp::ThreadIdxY { dst } => {
                self.emit_line(&format!("mov.u32 %r{}, %tid.y;", dst));
            }
            CudeadOp::ThreadIdxZ { dst } => {
                self.emit_line(&format!("mov.u32 %r{}, %tid.z;", dst));
            }
            CudeadOp::BlockIdxX { dst } => {
                self.emit_line(&format!("mov.u32 %r{}, %ctaid.x;", dst));
            }
            CudeadOp::BlockIdxY { dst } => {
                self.emit_line(&format!("mov.u32 %r{}, %ctaid.y;", dst));
            }
            CudeadOp::BlockIdxZ { dst } => {
                self.emit_line(&format!("mov.u32 %r{}, %ctaid.z;", dst));
            }
            CudeadOp::BlockDimX { dst } => {
                self.emit_line(&format!("mov.u32 %r{}, %ntid.x;", dst));
            }
            CudeadOp::BlockDimY { dst } => {
                self.emit_line(&format!("mov.u32 %r{}, %ntid.y;", dst));
            }
            CudeadOp::BlockDimZ { dst } => {
                self.emit_line(&format!("mov.u32 %r{}, %ntid.z;", dst));
            }
            CudeadOp::GridDimX { dst } => {
                self.emit_line(&format!("mov.u32 %r{}, %nctaid.x;", dst));
            }
            CudeadOp::GridDimY { dst } => {
                self.emit_line(&format!("mov.u32 %r{}, %nctaid.y;", dst));
            }
            CudeadOp::GridDimZ { dst } => {
                self.emit_line(&format!("mov.u32 %r{}, %nctaid.z;", dst));
            }

            // Control flow
            CudeadOp::Branch { target } => {
                self.emit_line(&format!("bra BB{};", target));
            }
            CudeadOp::BranchCond {
                cond,
                target_true,
                target_false,
            } => {
                self.emit_line(&format!("@%p{} bra BB{};", cond, target_true));
                self.emit_line(&format!("bra BB{};", target_false));
            }
            CudeadOp::Label { id } => {
                // Labels are emitted at block level
                let _ = id;
            }
            CudeadOp::Return => {
                self.emit_line("ret;");
            }

            // Synchronization
            CudeadOp::SyncThreads => {
                self.emit_line("bar.sync 0;");
            }
            CudeadOp::MemoryFence => {
                self.emit_line("membar.gl;");
            }

            // Comparison
            CudeadOp::Cmp {
                dst,
                src1,
                src2,
                op,
                ty,
            } => {
                let (prefix, suffix) = self.reg_info(ty);
                let cmp_op = op.to_ptx();
                self.emit_line(&format!(
                    "setp{}{} %p{}, {}{}, {}{};",
                    cmp_op, suffix, dst, prefix, src1, prefix, src2
                ));
            }

            // Conversion
            CudeadOp::Convert { dst, src, from, to } => {
                let (from_prefix, from_suffix) = self.reg_info(from);
                let (to_prefix, to_suffix) = self.reg_info(to);
                self.emit_line(&format!(
                    "cvt{}{} {}{}, {}{};",
                    to_suffix, from_suffix, to_prefix, dst, from_prefix, src
                ));
            }

            // Constants
            CudeadOp::Const { dst, value } => {
                match value {
                    IrConst::I32(v) => {
                        self.emit_line(&format!("mov.s32 %r{}, {};", dst, v));
                    }
                    IrConst::I64(v) => {
                        self.emit_line(&format!("mov.s64 %rd{}, {};", dst, v));
                    }
                    IrConst::U32(v) => {
                        self.emit_line(&format!("mov.u32 %r{}, {};", dst, v));
                    }
                    IrConst::U64(v) => {
                        self.emit_line(&format!("mov.u64 %rd{}, {};", dst, v));
                    }
                    IrConst::F32(v) => {
                        self.emit_line(&format!("mov.f32 %f{}, 0F{:08X};", dst, v.to_bits()));
                    }
                    IrConst::F64(v) => {
                        self.emit_line(&format!("mov.f64 %fd{}, 0D{:016X};", dst, v.to_bits()));
                    }
                }
            }

            // Parameter load
            CudeadOp::LoadParam { dst, param_idx, ty } => {
                let (prefix, suffix) = self.reg_info(ty);
                self.emit_line(&format!(
                    "ld.param{} {}{}, [param_{}];",
                    suffix, prefix, dst, param_idx
                ));
            }

            // Phi (SSA) - handled during register allocation
            CudeadOp::Phi { dst, sources, ty } => {
                // Phi nodes are resolved during register allocation
                // For now, emit a comment
                self.emit_line(&format!(
                    "// phi %r{} = {:?} : {:?}",
                    dst, sources, ty
                ));
            }
        }

        Ok(())
    }

    fn reg_info(&self, ty: &IrType) -> (&'static str, &'static str) {
        match ty {
            IrType::I32 => ("%r", ".s32"),
            IrType::I64 => ("%rd", ".s64"),
            IrType::U32 => ("%r", ".u32"),
            IrType::U64 => ("%rd", ".u64"),
            IrType::F32 => ("%f", ".f32"),
            IrType::F64 => ("%fd", ".f64"),
            IrType::Pred => ("%p", ".pred"),
            IrType::Ptr => ("%rd", ".u64"),
        }
    }
}

impl Default for PtxEmitter {
    fn default() -> Self {
        Self::new(GpuArch::Ampere)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::backend::gpu::cudead::primitives::KernelDef;

    #[test]
    fn test_ptx_header() {
        let emitter = PtxEmitter::new(GpuArch::Ampere);
        let mut e = PtxEmitter::new(emitter.arch);
        e.emit_header();
        assert!(e.output.contains(".version"));
        assert!(e.output.contains(".target sm_86"));
    }

    #[test]
    fn test_ptx_kernel() {
        let def = KernelDef::new("test", KernelType::Kernel);
        let kernel = KernelIR::new(&def);
        let ir = CudeadIR {
            kernels: vec![kernel],
            device_functions: vec![],
            shared_memory_total: 0,
        };

        let emitter = PtxEmitter::new(GpuArch::Ampere);
        let ptx = emitter.emit_ir(&ir).unwrap();
        assert!(ptx.contains(".entry test"));
    }
}
