# build_stdlib.ps1 — Compile all .pasm functions into a single asm_stdlib.obj
# Usage: .\build_stdlib.ps1 [-AsmBibPath <path>]
#
# Requires: ASM-BIB compiled (cargo build --release in ASM-BIB directory)
# Output: asm_stdlib.obj in the current directory

param(
    [string]$AsmBibPath = "$PSScriptRoot\..\..\..\..\ASM-BIB",
    [string]$OutputDir = "$PSScriptRoot"
)

$ErrorActionPreference = "Stop"

# Find ASM-BIB binary
$AsmBib = Join-Path $AsmBibPath "target\release\asm-bib.exe"
if (-not (Test-Path $AsmBib)) {
    $AsmBib = Join-Path $AsmBibPath "target\debug\asm-bib.exe"
}
if (-not (Test-Path $AsmBib)) {
    Write-Host "[ERROR] asm-bib.exe not found. Build ASM-BIB first:" -ForegroundColor Red
    Write-Host "  cd $AsmBibPath && cargo build --release" -ForegroundColor Yellow
    exit 1
}

$FunctionsDir = Join-Path $PSScriptRoot "functions"
$PasmFiles = Get-ChildItem -Path $FunctionsDir -Filter "*.pasm" | Sort-Object Name

if ($PasmFiles.Count -eq 0) {
    Write-Host "[ERROR] No .pasm files found in $FunctionsDir" -ForegroundColor Red
    exit 1
}

Write-Host "=== ASM-BIB stdlib build ===" -ForegroundColor Cyan
Write-Host "  ASM-BIB: $AsmBib"
Write-Host "  Sources: $($PasmFiles.Count) .pasm files"
Write-Host ""

# Strategy: Concatenate all .pasm into one combined source, then compile once
# This produces a single .obj with all functions as exported symbols.

$CombinedSource = Join-Path $OutputDir "asm_stdlib_combined.pasm"
$CombinedObj = Join-Path $OutputDir "asm_stdlib.obj"

# Concatenate all .pasm files
$Content = @()
$Content += "; asm_stdlib_combined.pasm — Auto-generated by build_stdlib.ps1"
$Content += "; DO NOT EDIT — regenerate with: .\build_stdlib.ps1"
$Content += ""
$Content += "format win64"
$Content += ""

foreach ($f in $PasmFiles) {
    $Content += "; === $($f.Name) ==="
    $Content += (Get-Content $f.FullName -Raw).TrimEnd()
    $Content += ""
}

$Content | Out-File -FilePath $CombinedSource -Encoding UTF8
Write-Host "  [1/2] Combined $($PasmFiles.Count) files -> asm_stdlib_combined.pasm" -ForegroundColor Green

# Compile with --native to produce COFF .obj directly
$Proc = Start-Process -FilePath $AsmBib -ArgumentList "$CombinedSource --native -o $CombinedObj" -NoNewWindow -PassThru -Wait

if ($Proc.ExitCode -ne 0) {
    Write-Host "  [ERROR] asm-bib --native failed (exit $($Proc.ExitCode))" -ForegroundColor Red
    exit 1
}

if (Test-Path $CombinedObj) {
    $Size = (Get-Item $CombinedObj).Length
    Write-Host "  [2/2] Compiled -> asm_stdlib.obj ($Size bytes)" -ForegroundColor Green
    Write-Host ""
    Write-Host "=== Done! ===" -ForegroundColor Cyan
    Write-Host "  Use with ADead-BIB:"
    Write-Host "    adB cc myfile.c --link-obj $CombinedObj" -ForegroundColor Yellow
} else {
    Write-Host "  [ERROR] Output .obj not found" -ForegroundColor Red
    exit 1
}
